package mesh.creator.special;

import mesh.Mesh3D;
import mesh.creator.FillType;
import mesh.creator.IMeshCreator;

/**
 * Creates a radially symmetric stepped pyramid mesh.
 *
 * <p>The geometry is generated by stacking polygonal ring segments with progressively decreasing
 * diameter. Each step consists of:
 *
 * <ul>
 *   <li>a vertical extrusion defined by {@code stepHeight}, and
 *   <li>a horizontal diameter reduction defined by {@code diameterReductionPerStep}.
 * </ul>
 *
 * <p>The base footprint is defined by {@code sidesCount}. A value of 4 produces a square stepped
 * pyramid, while higher values approximate a circular shape.
 *
 * <p>This generator can be used to create:
 *
 * <ul>
 *   <li>Classic step pyramids
 *   <li>Ziggurats
 *   <li>Stylized towers
 *   <li>Procedural low-poly architectural elements
 * </ul>
 *
 * <p>The diameter decreases linearly with each step. If the total diameter reduction exceeds the
 * initial diameter, the generated geometry will collapse or invert. This behavior is intentional
 * and mirrors the Blender “Mesh Extras – Step Pyramid” generator.
 *
 * <p>To avoid inversion, ensure:
 *
 * <pre>
 * stepsCount * diameterReductionPerStep <= initialDiameter
 * </pre>
 *
 * If the diameter becomes zero or negative, geometry may become non-manifold or contain degenerate
 * faces. This behavior is allowed and not automatically corrected.
 */
public class StepPyramidCreator implements IMeshCreator {

  /** Number of radial segments (minimum 3). */
  private int sidesCount = 4;

  /** Number of vertical steps (minimum 1). */
  private int stepsCount = 10;

  /** Height of a single step (must be > 0). */
  private float stepHeight = 0.1f;

  /** Initial base diameter (must be > 0). */
  private float initialDiameter = 2f;

  /** Linear diameter reduction applied per step (must be >= 0). */
  private float diameterReductionPerStep = 0.2f;

  /** Fill type used for the top cap. */
  private FillType topCapFillType = FillType.N_GON;

  /** Fill type used for the bottom cap. */
  private FillType bottomCapFillType = FillType.N_GON;

  /**
   * Generates the stepped pyramid mesh using a {@link VariableCylinderCreator}.
   *
   * @return a new {@link Mesh3D} instance representing the stepped pyramid
   */
  @Override
  public Mesh3D create() {
    float radius = initialDiameter * 0.5f;
    float reductionPerStep = diameterReductionPerStep * 0.5f;

    VariableCylinderCreator creator = new VariableCylinderCreator();
    creator.setRotationSegments(sidesCount);
    creator.setCapTopFillType(topCapFillType);
    creator.setCapBottomFillType(bottomCapFillType);

    for (int i = 0; i < stepsCount; i++) {
      float currentRadius = radius - (i * reductionPerStep);

      creator.addRingSegment(currentRadius, 0f);
      creator.addRingSegment(currentRadius, stepHeight);
    }

    return creator.create();
  }

  /** @return the number of radial sides */
  public int getSidesCount() {
    return sidesCount;
  }

  /**
   * Sets the number of radial sides.
   *
   * @param sidesCount number of sides (must be >= 3)
   * @throws IllegalArgumentException if {@code sidesCount < 3}
   */
  public void setSidesCount(int sidesCount) {
    if (sidesCount < 3) {
      throw new IllegalArgumentException("sidesCount must be >= 3.");
    }
    this.sidesCount = sidesCount;
  }

  /** @return the number of vertical steps */
  public int getStepsCount() {
    return stepsCount;
  }

  /**
   * Sets the number of vertical steps.
   *
   * @param stepsCount number of steps (must be >= 1)
   * @throws IllegalArgumentException if {@code stepsCount < 1}
   */
  public void setStepsCount(int stepsCount) {
    if (stepsCount < 1) {
      throw new IllegalArgumentException("stepsCount must be >= 1.");
    }
    this.stepsCount = stepsCount;
  }

  /** @return the height of a single step */
  public float getStepHeight() {
    return stepHeight;
  }

  /**
   * Sets the height of each step.
   *
   * @param stepHeight height per step (must be > 0)
   * @throws IllegalArgumentException if {@code stepHeight <= 0}
   */
  public void setStepHeight(float stepHeight) {
    if (stepHeight <= 0f) {
      throw new IllegalArgumentException("stepHeight must be > 0.");
    }
    this.stepHeight = stepHeight;
  }

  /** @return the initial base diameter */
  public float getInitialDiameter() {
    return initialDiameter;
  }

  /**
   * Sets the initial base diameter.
   *
   * @param initialDiameter base diameter (must be > 0)
   * @throws IllegalArgumentException if {@code initialDiameter <= 0}
   */
  public void setInitialDiameter(float initialDiameter) {
    if (initialDiameter <= 0f) {
      throw new IllegalArgumentException("initialDiameter must be > 0.");
    }
    this.initialDiameter = initialDiameter;
  }

  /** @return the diameter reduction per step */
  public float getDiameterReductionPerStep() {
    return diameterReductionPerStep;
  }

  /**
   * Sets the diameter reduction per step.
   *
   * @param diameterReductionPerStep reduction per step (must be >= 0)
   * @throws IllegalArgumentException if {@code diameterReductionPerStep < 0}
   */
  public void setDiameterReductionPerStep(float diameterReductionPerStep) {
    if (diameterReductionPerStep < 0f) {
      throw new IllegalArgumentException("diameterReductionPerStep must be >= 0.");
    }
    this.diameterReductionPerStep = diameterReductionPerStep;
  }

  /** @return the top cap fill type */
  public FillType getTopCapFillType() {
    return topCapFillType;
  }

  /**
   * Sets the fill type for the top cap.
   *
   * @param topCapFillType cap fill type (must not be {@code null})
   * @throws IllegalArgumentException if {@code topCapFillType == null}
   */
  public void setTopCapFillType(FillType topCapFillType) {
    if (topCapFillType == null) {
      throw new IllegalArgumentException("topCapFillType must not be null.");
    }
    this.topCapFillType = topCapFillType;
  }

  /** @return the bottom cap fill type */
  public FillType getBottomCapFillType() {
    return bottomCapFillType;
  }

  /**
   * Sets the fill type for the bottom cap.
   *
   * @param bottomCapFillType cap fill type (must not be {@code null})
   * @throws IllegalArgumentException if {@code bottomCapFillType == null}
   */
  public void setBottomCapFillType(FillType bottomCapFillType) {
    if (bottomCapFillType == null) {
      throw new IllegalArgumentException("bottomCapFillType must not be null.");
    }
    this.bottomCapFillType = bottomCapFillType;
  }
}
