package math.sampling;

import java.util.ArrayList;
import java.util.List;

import math.Vector2f;
import math.noise.Noise2D;

/**
 * Decorator sampler that applies a noise-based density mask to another sampler.
 *
 * <p>Points generated by the wrapped sampler are accepted or rejected based on a noise value
 * sampled at each point position. This allows smooth density variation, clearings, and natural
 * clustering without modifying the underlying sampling algorithm.
 *
 * <p>This sampler is deterministic with respect to the provided seed.
 */
public final class NoiseMaskedSampler implements PointSampler2D {

  private final PointSampler2D baseSampler;
  private final Noise2D noise;
  private final float threshold;
  private final float scale;

  /**
   * Creates a noise-masked sampler.
   *
   * @param baseSampler the underlying sampler to generate candidate points
   * @param noise noise function returning values in [0, 1]
   * @param threshold minimum noise value required for a point to be accepted
   * @param scale scale factor applied to point coordinates before noise sampling
   */
  public NoiseMaskedSampler(
      PointSampler2D baseSampler, Noise2D noise, float threshold, float scale) {
    this.baseSampler = baseSampler;
    this.noise = noise;
    this.threshold = threshold;
    this.scale = scale;
  }

  @Override
  public List<Vector2f> sample(float width, float height, long seed) {
    List<Vector2f> candidates = baseSampler.sample(width, height, seed);
    List<Vector2f> result = new ArrayList<>(candidates.size());

    for (Vector2f p : candidates) {
      float n = noise.sample(p.x * scale, p.y * scale);

      if (n >= threshold) {
        result.add(p);
      }
    }

    return result;
  }
}
