package mesh.sandbox;

import java.util.HashSet;
import java.util.Set;

import math.Mathf;
import math.Vector3f;
import mesh.Face3D;
import mesh.Mesh3D;
import mesh.creator.IMeshCreator;
import mesh.creator.special.VariableCylinderCreator;
import mesh.modifier.topology.ExtrudeModifier;
import mesh.modifier.topology.InsetModifier;
import mesh.selection.FaceSelection;

/**
 * Procedural mesh generator for a metal oil/steel barrel.
 *
 * <p>This creator builds a parameterized barrel mesh based on a variable-radius cylinder profile.
 * The final geometry is generated in multiple stages:
 *
 * <ol>
 *   <li>Construction of a vertical cylinder profile with configurable segment heights.
 *   <li>Addition of smooth radial bulges using sinusoidal radius modulation.
 *   <li>Inset and inward extrusion of top and bottom faces to create the barrel rim.
 *   <li>Additional scaling and extrusion on the top faces to form a raised cap.
 * </ol>
 *
 * <p>The barrel shape is fully procedural and can be customized via:
 *
 * <ul>
 *   <li>Radial resolution ({@code radialSegments})
 *   <li>Segment heights (top/middle/bottom)
 *   <li>Number and shape of bulges
 *   <li>Inset thickness
 *   <li>Cap radius and height
 * </ul>
 *
 * <p>Bulges are generated using a sine-based falloff to ensure smooth transitions between
 * cylindrical segments.
 *
 * <p>Inspired by: The CG Essentials – Oil Barrel Tutorial
 * https://www.youtube.com/watch?v=GUDC0D8mszo
 */
public class MetalBarrelCreator implements IMeshCreator {

  private float radius = 1f;

  private int radialSegments = 32;

  private float topSegmentHeight = 0.5f;

  private float midSegmentHeight = 1.5f;

  private float bottomSegmentHeight = 0.5f;

  private int bottomBulgeCount = 2;

  private int topBulgeCount = 2;

  private float inwardExtrude = 0.05f;

  private float inset = 0.2f; // aka barrel thickness

  private float bulgeHeight = 0.1f;

  private int bulgeSegments = 7;

  private float bulgeDepth = 0.04f;

  private float capRadius = 0.1f;

  private float capHeight = 0.05f;

  /**
   * Adds a smooth radial bulge segment to the given {@link VariableCylinderCreator}.
   *
   * <p>The bulge is generated by subdividing the vertical bulge height into {@code bulgeSegments}
   * slices. Each slice increases the radius using a sinusoidal function:
   *
   * <pre>
   * bulge = bulgeDepth * sin(PI * t)
   * </pre>
   *
   * where {@code t} is normalized in the range [0, 1].
   *
   * <p>This results in a smooth convex profile that blends seamlessly into the surrounding
   * cylindrical segments.
   *
   * @param creator the cylinder profile builder to which the bulge segments are added
   */
  private void addBulge(VariableCylinderCreator creator) {
    float step = bulgeHeight / bulgeSegments;

    for (int i = 1; i <= bulgeSegments; i++) {
      float t = (float) i / bulgeSegments; // normalized 0 → 1
      float bulge = bulgeDepth * Mathf.sin(Mathf.PI * t);

      creator.addRingSegment(radius + bulge, step);
    }
  }

  /**
   * Generates the complete barrel mesh.
   *
   * <p>Pipeline overview:
   *
   * <ol>
   *   <li>Build variable-radius cylinder profile with bulges.
   *   <li>Select top and bottom faces using normal-based selection.
   *   <li>Inset both ends to define barrel thickness.
   *   <li>Extrude inward to form the characteristic rim/lip.
   *   <li>Scale and extrude top faces to generate the barrel cap.
   * </ol>
   *
   * @return a fully constructed {@link Mesh3D} representing the barrel
   */
  @Override
  public Mesh3D create() {
    VariableCylinderCreator creator = new VariableCylinderCreator();
    creator.setRotationSegments(radialSegments);

    // 1. Generate cylinder profile
    addBulge(creator); // Bottom most bulge
    creator.addRingSegment(radius, bottomSegmentHeight); // Bottom segment

    for (int i = 0; i < bottomBulgeCount; i++) {
      addBulge(creator);
    }

    creator.addRingSegment(radius, midSegmentHeight); // Mid Segment

    for (int i = 0; i < topBulgeCount; i++) {
      addBulge(creator);
    }

    creator.addRingSegment(radius, topSegmentHeight); // Top segment
    addBulge(creator); // Top most bulge

    Mesh3D mesh = creator.create();

    // 2. Select end faces for modification
    FaceSelection topFaces = new FaceSelection(mesh);
    topFaces.selectSimilarNormal(new Vector3f(0, -1, 0), 0.001f);

    FaceSelection bottomFaces = new FaceSelection(mesh);
    bottomFaces.selectSimilarNormal(new Vector3f(0, 1, 0), 0.001f);

    // Combined selection for operations affecting both ends
    FaceSelection bothEnds = new FaceSelection(mesh);
    bothEnds.addAll(topFaces);
    bothEnds.addAll(bottomFaces);

    // 3. Apply Inset to both ends
    InsetModifier insetModifier = new InsetModifier();
    insetModifier.setInset(inset);
    insetModifier.modify(mesh, bothEnds.getFaces());

    // 4. Extrude Inwards to create barrel lip
    ExtrudeModifier extrudeModifier = new ExtrudeModifier();
    extrudeModifier.setAmount(-inwardExtrude);
    extrudeModifier.setScale(1);
    extrudeModifier.modify(mesh, bothEnds.getFaces());

    // 5. Cap Logic (Top only)
    float innerRadius = radius - inset;
    float percentage = capRadius / innerRadius; // Ensure correct scaling ratio

    extrudeModifier.setScale(percentage);
    extrudeModifier.setAmount(0);
    extrudeModifier.modify(mesh, topFaces.getFaces());

    // Calculate necessary shift to center the cap if needed (example logic)
    float shiftAmount = radius - inset - capRadius;
    Set<Integer> uniqueVertexIndices = new HashSet<>();
    for (Face3D f : topFaces.getFaces()) {
      for (int i = 0; i < f.getVertexCount(); i++) {
        uniqueVertexIndices.add(f.getIndexAt(i));
      }
    }

    // Apply shift only once per vertex
    for (int vertexIndex : uniqueVertexIndices) {
      Vector3f v = mesh.getVertexAt(vertexIndex);
      v.addLocal(-shiftAmount, 0, 0);
    }
    // ----------------------------------------------------

    // 6. Extrude top cap upwards
    extrudeModifier.setScale(1);
    extrudeModifier.setAmount(capHeight);
    extrudeModifier.modify(mesh, topFaces.getFaces());

    return mesh;
  }

  // =========================================================================
  // Getters & Fluent Setters
  // =========================================================================

  public float getRadius() {
    return radius;
  }

  /** @param radius Main radius of the barrel. */
  public MetalBarrelCreator setRadius(float radius) {
    this.radius = radius;
    return this;
  }

  public int getRadialSegments() {
    return radialSegments;
  }

  /** @param radialSegments Number of subdivisions around the cylinder. */
  public MetalBarrelCreator setRadialSegments(int radialSegments) {
    this.radialSegments = radialSegments;
    return this;
  }

  public float getTopSegmentHeight() {
    return topSegmentHeight;
  }

  /** @param topSegmentHeight Height of the top cylindrical segment. */
  public MetalBarrelCreator setTopSegmentHeight(float topSegmentHeight) {
    this.topSegmentHeight = topSegmentHeight;
    return this;
  }

  public float getMidSegmentHeight() {
    return midSegmentHeight;
  }

  /** @param midSegmentHeight Height of the main body cylindrical segment. */
  public MetalBarrelCreator setMidSegmentHeight(float midSegmentHeight) {
    this.midSegmentHeight = midSegmentHeight;
    return this;
  }

  public float getBottomSegmentHeight() {
    return bottomSegmentHeight;
  }

  /** @param bottomSegmentHeight Height of the bottom cylindrical segment. */
  public MetalBarrelCreator setBottomSegmentHeight(float bottomSegmentHeight) {
    this.bottomSegmentHeight = bottomSegmentHeight;
    return this;
  }

  public int getBottomBulgeCount() {
    return bottomBulgeCount;
  }

  /** @param bottomBulgeCount Number of bulge rings below the mid segment. */
  public MetalBarrelCreator setBottomBulgeCount(int bottomBulgeCount) {
    this.bottomBulgeCount = bottomBulgeCount;
    return this;
  }

  public int getTopBulgeCount() {
    return topBulgeCount;
  }

  /** @param topBulgeCount Number of bulge rings above the mid segment. */
  public MetalBarrelCreator setTopBulgeCount(int topBulgeCount) {
    this.topBulgeCount = topBulgeCount;
    return this;
  }

  public float getInwardExtrude() {
    return inwardExtrude;
  }

  /** @param inwardExtrude Depth of the rim extrusion. */
  public MetalBarrelCreator setInwardExtrude(float inwardExtrude) {
    this.inwardExtrude = inwardExtrude;
    return this;
  }

  public float getInset() {
    return inset;
  }

  /** @param inset Thickness of the barrel wall. */
  public MetalBarrelCreator setInset(float inset) {
    this.inset = inset;
    return this;
  }

  public float getBulgeHeight() {
    return bulgeHeight;
  }

  /** @param bulgeHeight Vertical height of a single bulge ring. */
  public MetalBarrelCreator setBulgeHeight(float bulgeHeight) {
    this.bulgeHeight = bulgeHeight;
    return this;
  }

  public int getBulgeSegments() {
    return bulgeSegments;
  }

  /** @param bulgeSegments Number of ring subdivisions per bulge. */
  public MetalBarrelCreator setBulgeSegments(int bulgeSegments) {
    this.bulgeSegments = bulgeSegments;
    return this;
  }

  public float getBulgeDepth() {
    return bulgeDepth;
  }

  /** @param bulgeDepth Maximum radius extension of the bulge. */
  public MetalBarrelCreator setBulgeDepth(float bulgeDepth) {
    this.bulgeDepth = bulgeDepth;
    return this;
  }

  public float getCapRadius() {
    return capRadius;
  }

  /** @param capRadius Radius of the raised top cap. */
  public MetalBarrelCreator setCapRadius(float capRadius) {
    this.capRadius = capRadius;
    return this;
  }

  public float getCapHeight() {
    return capHeight;
  }

  /** @param capHeight Height of the raised top cap. */
  public MetalBarrelCreator setCapHeight(float capHeight) {
    this.capHeight = capHeight;
    return this;
  }
}
